print("|**********CALCULATOR**********|")
a = input ("Enter first number:")
b = input ("Enter second number:")
print ("First number is:",a)
print ("Second number is:",b)
print("Additon of two number is       :",int(a)+int(b)) 
print("Subtraction of two number is   :",int(a)-int(b))
print("Multiplication of two number is:",int(a)*int(b))
print("Division of two number is      :",int(a)/int(b))
print("Floor Division of two number is:",int(a)//int(b))  
print("Reminder of two number is      :",int(a)%int(b))   
print("Power of",a,"is",b,"             :",int(a)**int(b))    